### PR TITLE
BUG: fix AttributeError in `dpnp.linalg.norm`

### PR DESCRIPTION
**Pull request by samir-nasibli**
## Description
fix `AttributeError: 'bool' object has no attribute 'astype'` in `dpnp.linalg.norm`

## Test
Current status (all related tests):
```bash
tests/test_linalg.py::test_norm1[0-0-[7]] PASSED  
tests/test_linalg.py::test_norm1[0-0-[1, 2]] PASSED
tests/test_linalg.py::test_norm1[0-0-[1, 0]] PASSED
tests/test_linalg.py::test_norm1[None-0-[7]] PASSED
tests/test_linalg.py::test_norm1[None-0-[1, 2]] PASSED
tests/test_linalg.py::test_norm1[None-0-[1, 0]] PASSED
tests/test_indexing.py::test_nonzero[[]] PASSED
tests/test_indexing.py::test_nonzero[[[0, 0], [0, 0]]] PASSED
tests/test_indexing.py::test_nonzero[[[1, 0], [1, 0]]] PASSED
tests/test_indexing.py::test_nonzero[[[1, 2], [3, 4]]] PASSED
tests/test_indexing.py::test_nonzero[[[0, 1, 2], [3, 0, 5], [6, 7, 0]]] PASSED
tests/test_indexing.py::test_nonzero[[[0, 1, 0, 3, 0], [5, 0, 7, 0, 9]]] PASSED
tests/test_indexing.py::test_nonzero[[[[1, 2], [0, 4]], [[0, 2], [0, 1]], [[0, 0], [3, 1]]]] PASSED
tests/test_indexing.py::test_nonzero[[[[[1, 2, 3], [3, 4, 5]], [[1, 2, 3], [2, 1, 0]]], [[[1, 3, 5], [3, 1, 0]], [[0, 1, 2], [1, 3, 4]]]]] PASSED
```

## TODO
__Finally will be fixed after #893__

### CODE REVIEW

**Comment by Alexander-Makaryev** [comment]
@samir-nasibli This is a bad workaround.
You hide type conversion in creating of new data container.
Error says that `'bool' object has no attribute 'astype'`, so we need to have a logic to process bool objects but not hide them.

**Comment by samir-nasibli** [comment]
> @samir-nasibli This is a bad workaround.
> You hide type conversion in creating of new data container.
> Error says that `'bool' object has no attribute 'astype'`, so we need to have a logic to process bool objects but not hide them.

@Alexander-Makaryev thank you for the comment
I implemented with using `count_nonzero` func, which doesn't require input array copy.

**Comment by Alexander-Makaryev** [comment]
@samir-nasibli  could you please remove skipping of tests from this PR? These fails are fixed in https://github.com/IntelPython/dpnp/pull/893

**Comment by samir-nasibli** [comment]
@Alexander-Makaryev we can review/merge it.

**Review by Alexander-Makaryev — APPROVED** [review]
LGTM
